// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeeg2YMRHRYZbnMAnrjiMOYr3uyKqaIM',
    appId: '1:464686597806:web:8b82d8038cb1c016b9cf3f',
    messagingSenderId: '464686597806',
    projectId: 'sfapp-6d665',
    authDomain: 'sfapp-6d665.firebaseapp.com',
    storageBucket: 'sfapp-6d665.appspot.com',
    measurementId: 'G-HKK69LZP6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NSrD2Nl1sS0dDerEZnt1vkBeynXjg4w',
    appId: '1:464686597806:android:11919eb2035f9e03b9cf3f',
    messagingSenderId: '464686597806',
    projectId: 'sfapp-6d665',
    storageBucket: 'sfapp-6d665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtiCAjiBsEOn9Ega8vmhOWzIxlZthr88',
    appId: '1:464686597806:ios:61c5d953614a544ab9cf3f',
    messagingSenderId: '464686597806',
    projectId: 'sfapp-6d665',
    storageBucket: 'sfapp-6d665.appspot.com',
    iosBundleId: 'com.example.sfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtiCAjiBsEOn9Ega8vmhOWzIxlZthr88',
    appId: '1:464686597806:ios:61c5d953614a544ab9cf3f',
    messagingSenderId: '464686597806',
    projectId: 'sfapp-6d665',
    storageBucket: 'sfapp-6d665.appspot.com',
    iosBundleId: 'com.example.sfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALeeg2YMRHRYZbnMAnrjiMOYr3uyKqaIM',
    appId: '1:464686597806:web:00ff12ec8a9b3a11b9cf3f',
    messagingSenderId: '464686597806',
    projectId: 'sfapp-6d665',
    authDomain: 'sfapp-6d665.firebaseapp.com',
    storageBucket: 'sfapp-6d665.appspot.com',
    measurementId: 'G-EGG94C1PXE',
  );
}
